### ISSUE TITLE
'Module not found' when loading step definitions

### ISSUE THREAD

**Issue by ziflit** [muralco/pickled-cucumber#12]
### Version
pickled-cucumber@2.1.0
cucumber@4.2.1
#### Observed behavior
Given any step definitions file `test/steps.ts`, when trying to run `$(npm bin)/cucumber-js -r ./test/steps.js` throws
```
Error: Cannot find module 'test/steps.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
    at Function.Module._load (internal/modules/cjs/loader.js:506:25)
    at Module.require (internal/modules/cjs/loader.js:636:17)
    at require (internal/modules/cjs/helpers.js:20:18)
...
```   
of which the relevant part is that the filename in the code was changed from `./test/steps.js` to `test/steps.js`. 

### Reasons
There is a similar bug reported in https://github.com/cucumber/cucumber-js/issues/1129#issuecomment-435102303 where the apparent culprit is `glob@7.0.6` which is the version that `cucumber@4.2.1` is pointing to. This was solved in https://github.com/cucumber/cucumber-js/commit/fee7e4b85f73699b770e3136c6885b7e55092d9f but that commit only was released as part of cucumber@5.0.0

### Solutions
Installing `glob@7.1.0` solves the issue.

**Comment by joac** [comment]
This issue was solved by latest release (`v3.0.0`) that uses the latest `@cucumber/cucumber` version
