### ISSUE TITLE
tsc has error about `Options` in `index.d.ts` - with TypeScript 3.7.4

### ISSUE THREAD

**Issue by mrseanryan** [muralco/pickled-cucumber#5]
When using `pickled-cucumber`  2.0.8 (or 2.0.9 or 2.0.10) as a dependency, and TypeScript 3.7.4, then there is a compile error.

tsc has an error about `Options` in `index.d.ts`

```
> tsc

node_modules/pickled-cucumber/index.d.ts:2:10 - error TS2440: Import declaration conflicts with local declaration of 'Options'.

2 import { Options, SetupFnArgs } from './types';
           ~~~~~~~

Found 1 error.
```

It seems to be caused by `Options` being re-declared in index.d.ts:

```
import { Options, SetupFnArgs } from './types';
export { getVariables } from './aliases';
export declare type Options = Options;
```

**Comment by nicolapalavecino** [comment]
I suppose you mean TS 3.7.3 released today or the other 3.7 versions. I found out that in TS 3.7 a new checking was [introduced](http://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#function-truthy-checks). I created a PR to fix this, I will inform you about progress on this. Thank you @mrseanryan for reporting this issue
